name: Test on SQLite

on: [ push ]

env:
  APP_DB_TYPE: sqlite

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        operating_system: ['ubuntu-22.04', 'ubuntu-24.04']
        php_versions:
          - '8.2'
          - '8.3'
          - '8.4'

    runs-on: '${{ matrix.operating_system }}'

    steps:
      - uses: actions/checkout@v3

      - name: 'SQLite version'
        run: |
          sqlite3 -version && php -r '$sqlite3 = new SQLite3(":memory:"); echo "SQLite version: " . $sqlite3->version()["versionString"] . PHP_EOL;'

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}

      - name: Install dependencies
        run: COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction

      - name: Run acceptance test cases
        run: sh ./test_sh

      - name: Run integration test cases
        run: php _vendor/bin/codecept run integration

      - name: Output logs
        if: failure()
        run: cat _cache/test/*.log && cat _tests/_output/email/*.txt && /home/runner/work/s2/s2/_tests/_output/
